### ISSUE TITLE
  File "../fgom/HMM.py", line 48, in _init     with open(self._tag_num_filepath, encoding="utf-8") as f: TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by JianyuZhao7** [chaoming0625/WaiMaiOpinionMiner#3]
Hi. It is a great project you have done. When I try to run this code, I met sth wrong.

  File "../fgom/HMM.py", line 48, in _init
    with open(self._tag_num_filepath, encoding="utf-8") as f:
TypeError: 'encoding' is an invalid keyword argument for this function

could you help me?

**Comment by chaoming0625** [comment]
You should use python 3. not Python 2.

**Comment by xieexiaotuzi** [comment]
Thank you so much
